### PR TITLE
🐛SQLite: fix Ironic container restarting issue

### LINKED ISSUE #562: Ironic container fails to restart with SQLite implementation
In case of SQLite usage the Ironic container fails to RESTART cause the SQL schema is already created.
`
ironic-1   | 2024-09-16 14:20:11.241 28 DEBUG oslo_db.api [-] Loading backend 'sqlalchemy' from 'ironic.db.sqlalchemy.api' _load_backend /usr/lib/python3.9/site-packages/oslo_db/api.py:259
ironic-1   | 2024-09-16 14:20:11.609 28 INFO alembic.runtime.migration [-] Context impl SQLiteImpl.
ironic-1   | 2024-09-16 14:20:11.609 28 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
ironic-1   | 2024-09-16 14:20:11.610 28 CRITICAL ironic [-] Unhandled error: oslo_db.exception.DBMigrationError: DB schema is already under version control. Use upgrade() instead
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic Traceback (most recent call last):
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic   File "/usr/bin/ironic-dbsync", line 8, in <module>
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic     sys.exit(main())
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic   File "/usr/lib/python3.9/site-packages/ironic/cmd/dbsync.py", line 343, in main
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic     CONF.command.func()
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic   File "/usr/lib/python3.9/site-packages/ironic/cmd/dbsync.py", line 134, in create_schema
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic     migration.create_schema()
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic   File "/usr/lib/python3.9/site-packages/ironic/db/migration.py", line 52, in create_schema
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic     return get_backend().create_schema()
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic   File "/usr/lib/python3.9/site-packages/ironic/db/sqlalchemy/migration.py", line 71, in create_schema
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic     raise db_exc.DBMigrationError("DB schema is already under version"
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic oslo_db.exception.DBMigrationError: DB schema is already under version control. Use upgrade() instead
ironic-1   | 2024-09-16 14:20:11.610 28 ERROR ironic 
`

### PR DESCRIPTION
**Pull request by blallau**
In case of SQLite implementation Ironic container fails to restart. create_schema will be called only when required.

fixes #562

### CODE REVIEW

File: scripts/ironic-common.sh [hunk 1]
```diff
@@ -87,8 +87,12 @@ run_ironic_dbsync()
         done
     else
         # SQLite does not support some statements. Fortunately, we can just create
-        # the schema in one go instead of going through an upgrade.
-        ironic-dbsync --config-file /etc/ironic/ironic.conf create_schema
+        # the schema in one go if not already created, instead of going through an upgrade
+        DB_VERSION="$(ironic-dbsync --config-file /etc/ironic/ironic.conf version)"
+        if [ "${DB_VERSION}" == "None" ];
```
Comment (tuminoid) [inline scripts/ironic-common.sh:92]:
```suggestion
        if [[ "${DB_VERSION}" == "None" ]]; then
```

File: scripts/ironic-common.sh [hunk 2]
```diff
@@ -87,8 +87,12 @@ run_ironic_dbsync()
...
+        then
```
Comment (tuminoid) [inline scripts/ironic-common.sh:93]:
```suggestion
```

**Review by tuminoid — COMMENTED** [review]
style nit

**Comment by tuminoid** [comment]
/ok-to-test

Please sign-off commit as well.

File: scripts/ironic-common.sh (hunk 2 above)
Comment (tuminoid) [reply scripts/ironic-common.sh]: You now have double then.

**Comment by tuminoid** [comment]
Should we cherry-pick this to release branches?

**Comment by elfosardo** [comment]
@tuminoid yes, up to release-24.0  I guess

**Comment by tuminoid** [comment]
> @tuminoid yes, up to release-24.0 I guess

Done, please approve.
