### PR TITLE
:bug: Fix runlogwatch script

### LINKED ISSUE #630: runlogwatch.sh seems broken by pyinotify in at least some jobs
The logs in https://github.com/metal3-io/baremetal-operator/actions/runs/13370277135/job/37696054576?pr=2113 look wild:

```
************ Contents of [0m<[0m[31m[1mEvent[0m/[34mmask[0m[0m=[0m[35m0x8[0m [34mmaskname[0m[0m=[0m[35mIN_CLOSE_WRITE[0m [34mname[0m[0m=[0m[35m4725b55f-e696-403b-8c43-d2bbff8d5e0f_inspection-rmtsnx~inspection-inspect_inspect_2025-02-24-08-34-12.tar.gz[0m [34mpath[0m[0m=[0m[35m/shared/log/ironic/deploy[0m [34mpathname[0m[0m=[0m[35m/shared/log/ironic/deploy/4725b55f-e696-403b-8c43-d2bbff8d5e0f_inspection-rmtsnx~inspection-inspect_inspect_2025-02-24-08-34-12.tar.gz[0m [34mwd[0m[0m=[0m[35m1[0m [0m>[0m ramdisk log file bundle **************
sed: -e expression #1, char 258: unknown option to `s'
tar (child): \033[0m<\033[0m\033[31m\033[1mEvent\033[0m/\033[34mmask\033[0m\033[0m=\033[0m\033[35m0x8\033[0m \033[34mmaskname\033[0m\033[0m=\033[0m\033[35mIN_CLOSE_WRITE\033[0m \033[34mname\033[0m\033[0m=\033[0m\033[35m4725b55f-e696-403b-8c43-d2bbff8d5e0f_inspection-rmtsnx~inspection-inspect_inspect_2025-02-24-08-34-12.tar.gz\033[0m \033[34mpath\033[0m\033[0m=\033[0m\033[35m/shared/log/ironic/deploy\033[0m \033[34mpathname\033[0m\033[0m=\033[0m\033[35m/shared/log/ironic/deploy/4725b55f-e696-403b-8c43-d2bbff8d5e0f_inspection-rmtsnx~inspection-inspect_inspect_2025-02-24-08-34-12.tar.gz\033[0m \033[34mwd\033[0m\033[0m=\033[0m\033[35m1\033[0m \033[0m>\033[0m: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

### PR DESCRIPTION
**Pull request by elfosardo**
Use correct values for read command, and remove colors from
output.
a pyinotify event looks like this:
\<Event dir=False mask=0x8 maskname=IN_CLOSE_WRITE name=mylogs.gzip path=/shared/log/ironic/deploy pathname=/shared/log/ironic/deploy/mylogs.gzip wd=1 \>
by default the output contains colorize text that is
interpreted literally by variable conversion in the
tar command, so not only we have to parse it, but
we also need to get just raw format output.

Signed-off-by: Riccardo Pittau <elfosardo@gmail.com>

Fixes #630

### CODE REVIEW

File: scripts/runlogwatch.sh [hunk 1]
```diff
@@ -5,9 +5,12 @@ LOG_DIR="/shared/log/ironic/deploy"
...
 mkdir -p "${LOG_DIR}"
 
+# shellcheck disable=SC2034
 python3 -m pyinotify -e IN_CLOSE_WRITE -v "${LOG_DIR}" |
-    while read -r path _action file; do
-        echo "************ Contents of ${path}/${file} ramdisk log file bundle **************"
-        tar -xOzvvf "${path}/${file}" | sed -e "s/^/${file}: /"
-        rm -f "${path}/${file}"
+    while read -r event dir mask maskname filename filepath pathname wd; do
+        FILENAME=$(echo "$filename" | cut -d'=' -f2- | sed -e 's/\x1b\[[0-9;]*m//g')
```
Comment (tuminoid) [inline scripts/runlogwatch.sh:11]:
```suggestion
        FILENAME=$(echo "${filename}" | cut -d'=' -f2- | sed -e 's/\x1b\[[0-9;]*m//g')
```
The above comment would also help understand what are we sed'ing here.

File: scripts/runlogwatch.sh [hunk 2]
```diff
@@ -5,9 +5,12 @@ LOG_DIR="/shared/log/ironic/deploy"
...
+        FILEPATH=$(echo "$filepath" | cut -d'=' -f2- | sed -e 's/\x1b\[[0-9;]*m//g')
```
Comment (tuminoid) [inline scripts/runlogwatch.sh:12]:
```suggestion
        FILEPATH=$(echo "${filepath}" | cut -d'=' -f2- | sed -e 's/\x1b\[[0-9;]*m//g')
```

File: scripts/runlogwatch.sh [hunk 3]
```diff
@@ -5,9 +5,12 @@ LOG_DIR="/shared/log/ironic/deploy"
 
 mkdir -p "${LOG_DIR}"
 
+# shellcheck disable=SC2034
 python3 -m pyinotify -e IN_CLOSE_WRITE -v "${LOG_DIR}" |
-    while read -r path _action file; do
-        echo "************ Contents of ${path}/${file} ramdisk log file bundle **************"
-        tar -xOzvvf "${path}/${file}" | sed -e "s/^/${file}: /"
-        rm -f "${path}/${file}"
+    while read -r event dir mask maskname filename filepath pathname wd; do
```
Comment (tuminoid) [inline scripts/runlogwatch.sh:10]: Can we add in a comment here what the pyinotify event looks like? It seems that we drastically go from 3 things to 7.

Please also add the same in the PR description, and also maybe why it ever worked with the 3 args before?

File: scripts/runlogwatch.sh [hunk 4]
```diff
@@ -5,9 +5,17 @@ LOG_DIR="/shared/log/ironic/deploy"
 
 mkdir -p "${LOG_DIR}"
 
+# shellcheck disable=SC2034
 python3 -m pyinotify -e IN_CLOSE_WRITE -v "${LOG_DIR}" |
```
Comment (tuminoid) [inline scripts/runlogwatch.sh:9]:
```suggestion
python3 -m pyinotify --raw-format -e IN_CLOSE_WRITE -v "${LOG_DIR}" |
```
This should disable the coloring of the output.
https://github.com/seb-m/pyinotify/blob/0f3f8950d12e4a6534320153eed1a90a778da4ae/python3/pyinotify.py#L2294

**Review by tuminoid — COMMENTED** [review]
We'll want to disable the colors.

(Checking the source repo.... uhh, changed 10+ years ago)

File: scripts/runlogwatch.sh (hunk 4 above)
Comment (elfosardo) [reply scripts/runlogwatch.sh:9]: I swear I looked for that option...........
thanks!

Comment (tuminoid) [reply scripts/runlogwatch.sh:9]: Forgot to commit it?

File: scripts/runlogwatch.sh [hunk 5]
```diff
@@ -5,9 +5,13 @@ LOG_DIR="/shared/log/ironic/deploy"
...
-    while read -r path _action file; do
-        echo "************ Contents of ${path}/${file} ramdisk log file bundle **************"
-        tar -xOzvvf "${path}/${file}" | sed -e "s/^/${file}: /"
-        rm -f "${path}/${file}"
+    while read -r event dir mask maskname filename filepath pathname wd; do
+        #NOTE(elfosardo): a pyinotify event looks like this:
+        # <Event dir=False mask=0x8 maskname=IN_CLOSE_WRITE name=mylogs.gzip path=/shared/log/ironic/deploy pathname=/shared/log/ironic/deploy/mylogs.gzip wd=1 >
+        FILENAME=$(echo "${filename}" | cut -d'=' -f2-)
```
Comment (tuminoid) [inline scripts/runlogwatch.sh:13]: Instead of parsing filename here, shouldn't we be using `pathname` which is full path including filename, so we don't need to use  `LOG_DIR+filename` on each line after this?

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by iurygregory — APPROVED** [review]
